name: vulcan_mobile_playground
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_supper_app_core:
    path: core

  cupertino_icons: ^1.0.8
  get_it: ^8.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.20.2
  flutter_blue_plus: ^2.3.8
  bloc: ^9.0.0
  bloc_concurrency: ^0.3.0
  flutter_bloc: ^9.1.0
  dartz: ^0.10.1
  equatable: ^2.0.7
  freezed_annotation: ^3.0.0
  fl_chart: ^1.2.0
  mcumgr_flutter: 0.8.1
  archive: ^4.0.7
  firebase_core: 3.12.1
  cloud_firestore: 5.6.5
  firebase_storage: 12.4.4
  flutter_gen: 5.14.1
  flutter_svg: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.15
  freezed: ^3.0.0
  flutter_gen_runner: 5.14.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/devices/
    - assets/images/devices/otherHand/
