// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsDNl6YzcPfhl-8pj3WOZEkKrwi2vs0nM',
    appId: '1:127457262772:android:e8bedf139304894ee2ebe1',
    messagingSenderId: '127457262772',
    projectId: 'vulcan-client',
    storageBucket: 'vulcan-client.appspot.com',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTkEaqXMCjPsdmwGIg9hOhoq0aoEHsZ6Y',
    appId: '1:127457262772:ios:2ebff40552fd6776e2ebe1',
    messagingSenderId: '127457262772',
    projectId: 'vulcan-client',
    storageBucket: 'vulcan-client.appspot.com',
    iosBundleId: 'com.example.vulcanMobilePlayground',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3PnA2YPNwvE2upkrtk4VSetbTl8XnAj0',
    appId: '1:127457262772:web:32827d40d6fe1e9ce2ebe1',
    messagingSenderId: '127457262772',
    projectId: 'vulcan-client',
    authDomain: 'vulcan-client.firebaseapp.com',
    storageBucket: 'vulcan-client.appspot.com',
    measurementId: 'G-NEPH8XZHY4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTkEaqXMCjPsdmwGIg9hOhoq0aoEHsZ6Y',
    appId: '1:127457262772:ios:2ebff40552fd6776e2ebe1',
    messagingSenderId: '127457262772',
    projectId: 'vulcan-client',
    storageBucket: 'vulcan-client.appspot.com',
    iosBundleId: 'com.example.vulcanMobilePlayground',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_GKx9XN5HHHzowQjPMu0fAs9Z85KehKw',
    appId: '1:127457262772:web:54e5541120cc996ee2ebe1',
    messagingSenderId: '127457262772',
    projectId: 'vulcan-client',
    authDomain: 'vulcan-client.firebaseapp.com',
    storageBucket: 'vulcan-client.appspot.com',
    measurementId: 'G-1DKPQN6DH2',
  );
}
